# Generated by Django 2.2.6 on 2019-10-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191006_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.TextField(choices=[('n', 'None'), ('m', 'Male'), ('f', 'Female')]),
        ),
    ]
