# Generated by Django 2.2.6 on 2019-10-25 05:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='user_info',
            field=models.ManyToManyField(through='order.Order', to=settings.AUTH_USER_MODEL),
        ),
    ]
