# Generated by Django 2.2.6 on 2019-10-25 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('returned_date', models.DateField(null=True)),
                ('books', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Books')),
            ],
        ),
    ]
