# Generated by Django 2.2.6 on 2019-10-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='returned_date',
            field=models.DateField(null=True),
        ),
    ]
