# Generated by Django 2.2.10 on 2020-02-23 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0003_auto_20200222_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.TextField(choices=[('pending', 1), ('approved', 2), ('declined', 3), ('done', 4)], default='pending')),
                ('is_cancelled', models.BooleanField(default=False)),
                ('expected_return_date', models.DateTimeField(blank=True, null=True)),
                ('actual_return_date', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_approval', to=settings.AUTH_USER_MODEL)),
                ('return_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_aproval', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='actual_return_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='expected_return_date',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderStatus'),
        ),
    ]
