# Generated by Django 2.2.10 on 2020-02-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20200223_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='approved_by',
            new_name='admin_action_by',
        ),
        migrations.AddField(
            model_name='order',
            name='admin_action_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
